### ISSUE TITLE
Edit group info after creation

### ISSUE THREAD

**Issue by philip-zhan** [philip-zhan/badminton-group#20]
Maybe also require a PIN when creating and editing groups， so that only the creator of the group and edit it.

**Comment by t3rryw1** [comment]
I have the same thought! also the PIN can be used for removing unwanted player from the signup list

**Comment by t3rryw1** [comment]
added to use owner PIN to remove player from the list.

**Comment by t3rryw1** [comment]
also see https://github.com/philip-zhan/badminton-group/pull/22
